version: "3.8"
services:
  gym-finder-database:
    container_name: gym-finder-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: dldnjsrms/gym-finder-database
    environment:
      - MARIADB_DATABASE=gym-finder
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  gym-finder-redis:
    container_name: gym-finder-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: dldnjsrms/gym-finder-redis
    ports:
      - "6379:6379"